global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    scheme: https
    static_configs:
      - targets: ['${API_TARGET}']
        
  - job_name: 'pushgateway'
    scheme: https
    honor_labels: true
    static_configs:
      - targets: ['${PUSHGATEWAY_TARGET}']

remote_write:
  - url: "${GRAFANA_CLOUD_URL}"
    basic_auth:
      username: "${GRAFANA_CLOUD_USER}"
      password: "${GRAFANA_CLOUD_API_KEY}"
