data:
  path: "data/dataset.csv"
  target_col: "loan_status"
  split_ratios:
    train: 0.7
    val: 0.15
    test: 0.15

features:
  leakage_cols: 
    - "total_pymnt"
    - "recoveries"
    - "last_pymnt_amnt"
    - "collection_recovery_fee"
    - "total_pymnt_inv"
    - "total_rec_prncp"
    - "total_rec_int"
    - "total_rec_late_fee"
    - "last_fico_range_high"
    - "last_fico_range_low"

model:
  xgboost_grid:
    max_depth: [3, 5]
    learning_rate: [0.01, 0.1]
    n_estimators: [100,200]

evaluation:
  cost_matrix:
    fn_cost: 10
    fp_cost: 1
